import {
  IconMenu2,
  IconX,
  IconArrowRight,
  IconArrowDown,
  IconArrowUpRight,
  IconExternalLinkFilled,
  IconMail,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconBookFilled,
  IconBriefcaseFilled,
  IconQuoteFilled,
  IconStarFilled,
  IconFileTextFilled,
  IconEyeFilled,
  IconBoltFilled,
  IconMagnetFilled,
  IconMicrophoneFilled,
  IconPresentationFilled,
  IconShieldCheckFilled,
  IconInfoCircleFilled,
  IconLoader2,
  IconCheck,
  IconUserFilled,
  IconDiamondFilled,
  IconSeedlingFilled,
  IconFlareFilled,
  IconAwardFilled,
  IconWorldFilled,
  IconSunHighFilled,
  IconMessageFilled,
  IconFolderFilled,
  IconGiftFilled,
  IconCrownFilled,
  IconHeartFilled,
  IconChessRookFilled,
} from "@tabler/icons-react";
import { IconCompassCustom, IconInstituteCustom } from "./CustomIcons";

export const iconMap = {
  menu: IconMenu2,
  close: IconX,
  "arrow-right": IconArrowRight,
  "arrow-down": IconArrowDown,
  "arrow-up-right": IconArrowUpRight,
  "external-link": IconExternalLinkFilled,
  mail: IconMail,
  "chevron-down": IconChevronDown,
  "chevron-left": IconChevronLeft,
  "chevron-right": IconChevronRight,
  compass: IconCompassCustom,
  institute: IconInstituteCustom,
  book: IconBookFilled,
  briefcase: IconBriefcaseFilled,
  quote: IconQuoteFilled,
  star: IconStarFilled,
  "file-text": IconFileTextFilled,
  eye: IconEyeFilled,
  bolt: IconBoltFilled,
  magnet: IconMagnetFilled,
  microphone: IconMicrophoneFilled,
  presentation: IconPresentationFilled,
  "shield-check": IconShieldCheckFilled,
  "info-circle": IconInfoCircleFilled,
  loader: IconLoader2,
  check: IconCheck,
  "user-filled": IconUserFilled,
  "diamond-filled": IconDiamondFilled,
  "seedling-filled": IconSeedlingFilled,
  "flare-filled": IconFlareFilled,
  "award-filled": IconAwardFilled,
  "world-filled": IconWorldFilled,
  "sun-high-filled": IconSunHighFilled,
  "message-filled": IconMessageFilled,
  "folder-filled": IconFolderFilled,
  "gift-filled": IconGiftFilled,
  "crown-filled": IconCrownFilled,
  "heart-filled": IconHeartFilled,
  "chess-rook-filled": IconChessRookFilled,
} as const;

export type IconName = keyof typeof iconMap;
