import {
  IconMenu2,
  IconX,
  IconArrowRight,
  IconArrowUpRight,
  IconExternalLinkFilled,
  IconMail,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconBookFilled,
  IconBriefcaseFilled,
  IconQuoteFilled,
  IconStarFilled,
  IconFileTextFilled,
  IconEyeFilled,
  IconBoltFilled,
  IconMagnetFilled,
  IconMicrophoneFilled,
  IconPresentationFilled,
  IconShieldCheckFilled,
} from "@tabler/icons-react";
import { IconCompassCustom, IconInstituteCustom } from "./CustomIcons";

export const iconMap = {
  menu: IconMenu2,
  close: IconX,
  "arrow-right": IconArrowRight,
  "arrow-up-right": IconArrowUpRight,
  "external-link": IconExternalLinkFilled,
  mail: IconMail,
  "chevron-down": IconChevronDown,
  "chevron-left": IconChevronLeft,
  "chevron-right": IconChevronRight,
  compass: IconCompassCustom,
  institute: IconInstituteCustom,
  book: IconBookFilled,
  briefcase: IconBriefcaseFilled,
  quote: IconQuoteFilled,
  star: IconStarFilled,
  "file-text": IconFileTextFilled,
  eye: IconEyeFilled,
  bolt: IconBoltFilled,
  magnet: IconMagnetFilled,
  microphone: IconMicrophoneFilled,
  presentation: IconPresentationFilled,
  "shield-check": IconShieldCheckFilled,
} as const;

export type IconName = keyof typeof iconMap;
